apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: pve
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pve.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: pve
spec:
  tls:
    secretName: wildcard-hyvel-certificate-secret
    domains:
      - main: pve.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`pve.hyvel.eu`)
      kind: Rule
      services:
        - kind: Service
          name: pve-svc
          port: 8006
          scheme: https
          serversTransport: pve-transport


---

apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pve-transport
  namespace: pve

spec:
  insecureSkipVerify: true
