apiVersion: v1
kind: ConfigMap
metadata:
  name: app
  namespace: dummy200
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    error_log /dev/stdout warn;
    pid /nginx.pid;

    events { worker_connections 1024; }

    http {
      include mime.types;

      access_log off;
      server_tokens off;

      sendfile on;
      tcp_nopush on;
      reset_timedout_connection on;
    
      keepalive_timeout 15s;
      client_body_timeout 15s;
      client_header_timeout 15s;
      send_timeout 15s;

      server {
        listen 80 default_server;
        server_name _;

        location / {
          default_type text/plain;
          return 200 "OK\n";
        }
      }
    }
