apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: bgp-cluster-config
  namespace: cilium
spec:
  bgpInstances:
    - name: main
      localASN: 64512
      peers:
        - name: router
          peerASN: 64512
          peerAddress: 192.168.0.1
          peerConfigRef:
            name: bgp-peer-config