apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: qbt
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data-sc-0
  resources:
    requests:
      storage: 1Gi
