apiVersion: v1
kind: Service
metadata:
  name: xui
  namespace: xui
  labels:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: xui
    app.kubernetes.io/component: app
  ports:
    - name: web
      protocol: TCP
      port: 7700
      targetPort: 7700
    - name: web-sub
      protocol: TCP
      port: 7560
      targetPort: 7560
    - name: xhttp-tls
      protocol: TCP
      port: 7552
      targetPort: 7552
    - name: raw-reality
      protocol: TCP
      port: 7553
      targetPort: 7553
    - name: xhttp-reality
      protocol: TCP
      port: 7554
      targetPort: 7554
  type: ClusterIP
