apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: traefik
spec:
  compress:
    excludedContentTypes:
      - image/*
      - video/*
      - audio/*
      - application/zip
      - application/x-zip-compressed
      - application/gzip
      - application/x-gzip
      - application/x-7z-compressed
      - application/pdf
      - application/octet-stream
      - font/woff2
      - font/woff
