apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-plain
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`traefik.ho.hyvel.eu`)
      middlewares:
        - name: traefik-https-redirect
          namespace: traefik
      kind: Rule
      services:
        - name: noop@internal
          kind: TraefikService

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: traefik
spec:
  tls:
    secretName: wildcard-ho-hyvel-certificate-secret
    domains:
      - main: traefik.ho.hyvel.eu
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.ho.hyvel.eu`)
      kind: Rule
      services:
        - kind: TraefikService
          name: api@internal
