apiVersion: v1
kind: Service
metadata:
  name: souin-cache
  namespace: traefik
  labels:
    app.kubernetes.io/name: souin
    app.kubernetes.io/component: cache
spec:
  selector:
    app.kubernetes.io/name: souin
    app.kubernetes.io/component: cache
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
