apiVersion: v1
kind: Service
metadata:
  name: ts
  namespace: ts
  labels:
    app.kubernetes.io/name: ts
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: ts
    app.kubernetes.io/component: app
  ports:
    - name: tcp
      protocol: TCP
      port: 7540
      targetPort: 7540
  type: ClusterIP
