apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: anubis
  labels:
    app.kubernetes.io/name: anubis
    app.kubernetes.io/component: app
spec:
  selector:
    app.kubernetes.io/name: anubis
    app.kubernetes.io/component: app
  ports:
    - port: 7580
      protocol: TCP
      targetPort: 7580
  type: ClusterIP
